name: CI workflow

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.x

    - name: Restore dependencies
      run: dotnet restore PCHCB/PCHCB.Tests/PCHCB.Tests.csproj

    - name: Build
      run: dotnet build PCHCB/PCHCB.Tests/PCHCB.Tests.csproj --configuration Release --no-restore

  test:
    needs: build
    runs-on: ubuntu-latest
  
    steps:
    - uses: actions/checkout@v2
  
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.x
  
    - name: Restore dependencies
      run: dotnet restore PCHCB/PCHCB.Tests/PCHCB.Tests.csproj
  
    - name: Test
      run: dotnet test PCHCB/PCHCB.Tests/PCHCB.Tests.csproj --no-restore --verbosity normal
